name: OSV-Scanner demo

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  scan:
    name: Check licenses
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install OSV-Scanner
      run: |
        go install github.com/google/osv-scanner/cmd/osv-scanner@v2.0.0-beta1
    - name: Run OSV-Scanner
      run: |
        osv-scanner scan source -r src
        osv-scanner --experimental-licenses-summary src
        osv-scanner --experimental-licenses="MIT,Apache-2.0" src
    - uses: actions/upload-artifact@v4
      with:
        path: $RUNNER_TEMP/reports



osv-scanner --experimental-licenses-summary path/to/repository
