name: Dependency Track demo

on:
  push:
    branches: [ "main", "13-create-sbom-and-upload-to-dtrack" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Generate XML SBOM
        uses: CycloneDX/gh-dotnet-generate-sbom@v1
        with:
          path: ./demo-app/TravelDestinationRecommender.sln
          github-bearer-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SBOM to Dependency-Track
        uses: DependencyTrack/gh-upload-sbom@v3
        with:
          serverHostname: isol-d1-appsrv-dtrack-api.azurewebsites.net
          apiKey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          project: '0becc5cc-1d9d-4822-a828-2972c5ffd90b'
