name: OWASP dep-scan demo

on:
  push:
    branches: ["main"]

jobs:
  scan:
    name: Create SBOM of .NET solution
    runs-on: ubuntu-latest
    env:
      FETCH_LICENSE: true

    steps:
      - uses: actions/checkout@v4
      - name: Install OWASP dep-scan
        run: |
          sudo npm install -g @cyclonedx/cdxgen
          pip install owasp-depscan
      - name: Run depscan
        run: |
          cd src/
          depscan --src ReactAndAspNetCoreApp.Server --reports-dir $RUNNER_TEMP/reports
      - uses: actions/upload-artifact@v4
        with:
          path: $RUNNER_TEMP/reports
