name: OWASP dep-scan demo

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  scan:
    name: Create SBOM of .NET solution
    runs-on: ubuntu-latest
    env:
      FETCH_LICENSE: true

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet build src/ReactAndAspNetCoreApp.sln --output buildOutput
    - name: Install OWASP dep-scan
      run: |
        sudo npm install -g @cyclonedx/cdxgen
        pip install owasp-depscan
    - name: Run OWASP dep-scan
      run: |
        depscan --src src/ReactAndAspNetCoreApp.Server --reports-dir $RUNNER_TEMP/reports -t dotnet,license --debug
    - uses: actions/upload-artifact@v4
      with:
        path: $RUNNER_TEMP/reports
